tahara test
OVaaS/ovaas-front pull request #18
Opened 2021-06-15 10:59 UTC by Arisahyper

2021-06-15 11:02 UTC, hannoeru approved these changes

2021-06-15 11:02 UTC, hannoeru commented
LGMT!

2021-08-23 00:20 UTC, hannoeru requested changes
JSON キーの修正お願いします！

2021-08-23 01:40 UTC, Arisahyper commented
了解です！
最初にtestという名前でPRを出したリポジトリは削除してしまったので、yoloを作成したリポジトリから新しくブランチを切ってPRを出す予定です
よろしくお願いします

2021-08-23 03:48 UTC, hannoeru commented
そうならばmainブランチから新しいフォークを作ってください、いくつの変更がありますので。

2021-08-23 03:48 UTC, closed without merging

2021-08-24 01:56 UTC, Arisahyper commented
フォークしないといけませんか？
新しくブランチを切ってリモートのmainブランチからpullする、ではダメですか？

2021-08-24 02:07 UTC, Arisahyper commented
すみません
pullしてみたところやはり変更が多く、かなりconflictしているのでcloneしなおそうと思います！