uchida:test
OVaaS/ovaas-front pull request #20
Opened 2021-06-15 13:10 UTC by Hoku113

これで大丈夫でしょうか？

2021-06-16 10:21 UTC, hannoeru requested changes
画像の名前は関連性がない、画像の内容もちょっと違うと思います

2021-06-16 17:33 UTC, hannoeru commented
Main ブランチとコンフリクトがあるので更新しました、作業を始める前にもう一度 pull してください

2021-06-18 13:53 UTC, Hoku113 commented
画像の部分を変更しました。確認をお願いします

2021-06-18 14:44 UTC, hannoeru approved these changes

2021-06-18 14:45 UTC, merged